### PR TITLE
Strange state after git pull

### PR DESCRIPTION
**Pull request by mremy**
Is it the right way to solve this state ?

Again a strange issue after "git pull".
I didn't change anything, after the last git pull, git status showed a modified file, so I just commit the state.
I suspect something with git configuration, or something like that, more than a latin1/utf8 issue.

short:
Maybe an auto convertion somewhere ?

long:
I'm on a local branch, used only to follow your repo.

`$ export LC_ALL=C
$ git log HEAD^..HEAD
commit 7549f684ab09a4eaf3917f0ea858c26c6c5adcf4
Author: Dennis Yurichev <dennis@yurichev.com>
Date:   Mon Jan 30 02:55:45 2017 +0200

    ...
$ git status
On branch master
Your branch is behind 'origin/master' by 7 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working directory clean
$ git pull
Updating 7549f68..e090727
Fast-forward
 OS/PE/main_DE.tex             | 198 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------------------------
 patterns/04_scanf/error.tex   |   2 ++
 patterns/04_scanf/main.tex    |   2 +-
 patterns/065_GOTO/main_DE.tex |  69 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 4 files changed, 176 insertions(+), 95 deletions(-)
 create mode 100644 patterns/04_scanf/error.tex
 create mode 100644 patterns/065_GOTO/main_DE.tex
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   ../../065_GOTO/main_DE.tex

no changes added to commit (use "git add" and/or "git commit -a")
$ git log HEAD^..HEAD
commit e0907274994c906ecb12008dd405366730d98c6d
Merge: 2075f49 3ee0131
Author: Dennis Yurichev <dennis@yurichev.com>
Date:   Wed Feb 1 04:33:15 2017 +0200

    Merge pull request #239 from DSiekmeier/master

    More german translations of OS

commit 3ee0131b1ebd4ae3fc077900060ca8aab59bd172
Author: DSiekmeier <contact@dsiekmeier.de>
Date:   Tue Jan 31 20:32:30 2017 +0100

    German translation of 'base address'

commit e468f2fcf4ccfc080008a1d665896f84e225bf5d
Author: DSiekmeier <contact@dsiekmeier.de>
Date:   Tue Jan 31 20:14:58 2017 +0100

    German translation Win32 PE
$ md5sum ../../065_GOTO/main_DE.tex
bcb59437c8f21ff5d5dc18907b828522  ../../065_GOTO/main_DE.tex
`
Now, sample of the problematic file.
It's not an latin1/UTF-8 issue:

$ git diff|grep "GOTO Operator wird"|hexdump -C
00000000  2d 44 65 72 20 47 4f 54  4f 20 4f 70 65 72 61 74  |-Der GOTO Operat|
00000010  6f 72 20 77 69 72 64 20  66 c3 bc 72 20 67 65 77  |or wird f..r gew|
00000020  c3 b6 68 6e 6c 69 63 68  20 61 6c 73 20 41 6e 74  |..hnlich als Ant|
00000030  69 2d 50 61 74 74 65 72  6e 20 61 6e 67 65 73 65  |i-Pattern angese|
00000040  68 65 6e 2c 20 76 67 6c  2e 20 64 61 7a 75 0d 0a  |hen, vgl. dazu..|
00000050  2b 44 65 72 20 47 4f 54  4f 20 4f 70 65 72 61 74  |+Der GOTO Operat|
00000060  6f 72 20 77 69 72 64 20  66 c3 bc 72 20 67 65 77  |or wird f..r gew|
00000070  c3 b6 68 6e 6c 69 63 68  20 61 6c 73 20 41 6e 74  |..hnlich als Ant|
00000080  69 2d 50 61 74 74 65 72  6e 20 61 6e 67 65 73 65  |i-Pattern angese|
00000090  68 65 6e 2c 20 76 67 6c  2e 20 64 61 7a 75 0a     |hen, vgl. dazu.|
0000009f

The "ü","ö" are well coded in both -line and +line (c3 bc, c3 b6).
The only difference is at EOL, 0d 0a in the - line, and 0a in the +line.
Very strange, because the .gitattributes "says":
*.tex text eol=crlf encoding=UTF-8

I even checked this in my .git/config: autocrlf = true / input (not both at the same time, and with git reset --hard + git pull). Problem still the same.

But, the oddest stuff is that the file actually have the 0d 0a:
$ hexdump -C ../../065_GOTO/main_DE.tex                                       
00000000  5c 73 65 63 74 69 6f 6e  7b 47 4f 54 4f 20 4f 70  |\section{GOTO Op|
00000010  65 72 61 74 6f 72 7d 0d  0a 0d 0a 44 65 72 20 47  |erator}....Der G|
00000020  4f 54 4f 20 4f 70 65 72  61 74 6f 72 20 77 69 72  |OTO Operator wir|
00000030  64 20 66 c3 bc 72 20 67  65 77 c3 b6 68 6e 6c 69  |d f..r gew..hnli|
00000040  63 68 20 61 6c 73 20 41  6e 74 69 2d 50 61 74 74  |ch als Anti-Patt|
00000050  65 72 6e 20 61 6e 67 65  73 65 68 65 6e 2c 20 76  |ern angesehen, v|
00000060  67 6c 2e 20 64 61 7a 75  0d 0a 5b 45 64 67 61 72  |gl. dazu..[Edgar|
[...]

I don't understand the git diff.

Of course, I tried: iconv -f latin1 -t utf-8 < file1 > file2
And several other source encoding.
But it was hopeless, as the character encoding is already utf8.
Still looking to understand what's happening.
Can someone explain?

### CODE REVIEW

**Comment by dennis714** [comment]
@DSiekmeier what git version do you use? Is it possible that your git ignores "eol=crlf" in .gitattributes?

**Comment by dennis714** [comment]
Meanwhile, I'm on commit 24a3dff59e0c1edce87cdeade85b16fcf5bd26af, md5sum results:
`% md5sum main_DE.tex`
`bcb59437c8f21ff5d5dc18907b828522  main_DE.tex`

main_DE.tex has both CR/LF's as EOLs.

... and "git status" commands shows nothing.

**Comment by mremy** [comment]
The file ./patterns/065_GOTO/main_DE.tex was in commit 89a024f4c1498b8032809d9f7756f361890efe7e from @JAngres

**Comment by dennis714** [comment]
OK, @JAngres , what EOLs your text editor use by default?

**Comment by mremy** [comment]
It's normal that the md5sum is still bcb59437c8f21ff5d5dc18907b828522 main_DE.tex in  24a3dff59e0c1edce87cdeade85b16fcf5bd26af, as my md5sum was after the "change".

By the way, I tried too to do: "git checkout -- ../../065_GOTO/main_DE.tex" to discard changes in working directory
but it has no effect, the state stay as is.

**Comment by DSiekmeier** [comment]
fyi: I am using git version 1.9.1 under Linux

**Comment by JAngres** [comment]
Sorry for the inconvenience. I'm currently using the Texlipse Eclipse plugin with UTF-8 encoding, OS is Win 7 so EOL should be Windows style as well.

Am 01.02.2017 um 11:48 schrieb Dennis Yurichev:

OK, @JAngres<https://github.com/JAngres> , what EOLs your text editor use by default?

**Comment by mremy** [comment]
I guess the EOL are fine, because the project use CRLF (windows style), as already wrote, the .gitattributes contains: "*.tex text eol=crlf encoding=UTF-8"
Am I the only one to see the strange git status after pull ?
What about you @DSiekmeier @dennis714 ?
At this point: "commit 24a3dff59e0c1edce87cdeade85b16fcf5bd26af", what give you a git status ?
Do you see same as me ? (already the case at commit  e0907274994c906ecb12008dd405366730d98c6d )
Sorry to bother, but I would like to understand this issue.
I'm using git 2.1.4 under Linux Debian stable.

**Comment by dennis714** [comment]
I had this state in past, but it's gone. Maybe because I did commit. Right now, when I checkout commits 24a3dff59e0c1edce87cdeade85b16fcf5bd26af or e0907274994c906ecb12008dd405366730d98c6d, "git status" is seems to be silent.

**Comment by mremy** [comment]
So if this happen again, just commit and "voilà" ?

**Comment by dennis714** [comment]
Yep, until we have a better understanding of the issue.

**Comment by dennis714** [comment]
FYI: md5sum of the main_DE.tex file hasn't been changed after I've merged your PR.

**Comment by dennis714** [comment]
http://stackoverflow.com/questions/5009096/files-showing-as-modified-directly-after-git-clone

**Comment by mremy** [comment]
At least I found the resaon, BOFH: EBADVERSION
I did some checks:
Debian 7.11 git 1.7.10.4 -> UNCLEAN
Debian 8.7 git 2.1.4 -> UNCLEAN
Ubuntu 10.04 LTS git 1.7.0.4  -> OK
Ubuntu 12.04 LTS git 1.7.9.5  -> UNCLEAN
Ubuntu 16.04 LTS git 2.7.4 -> UNCLEAN
Ubuntu 16.10 git 2.9.3 -> UNCLEAN
I looked for issue with git/windows/utf8 and went here:
http://stackoverflow.com/questions/5854967/git-msysgit-accents-utf-8-the-definitive-answers                                                                                                                     
https://github.com/kblees/git/wiki

I decided to have a look in the git object and found the cause of this issue:
The blob (which contains a file) commits from @JAngres have line ending with CRLF, and git store it (on blob level) with only LF.

Long version (come from a script output, with control characted manually removed, it's possible that I removed too much, but the idea is here):
sh-4.3$ git clone https://github.com/dennis714/RE-for-beginners.git
Cloning into 'RE-for-beginners'...
remote: Counting objects: 38593, done.
[...]
Checking connectivity... done.
sh-4.3$ git log patterns/065_GOTO/main_DE.tex
fatal: Not a git repository (or any of the parent directories): .git

sh-4.3$ cd RE-for-beginners/

sh-4.3$ git log patterns/065_GOTO/main_DE.tex
commit 0480d1ada862e0e6857c687dd3dbb59520724a54
Author: Marc Remy <mremy@gmx.ch>
Date:   Wed Feb 1 11:13:55 2017 +0100

    Strange state after git pull
    
    I didn't change anything, after the last git pull, git status showed a modified file, so I just commit the state.
    Maybe an auto convertion somewhere ?

commit 89a024f4c1498b8032809d9f7756f361890efe7e
Author: Julius Angres <julius.angres@outlook.de>
Date:   Tue Jan 31 21:47:00 2017 +0100

    German translation

First, search for file commited by @JAngres 
sh-4.3$ git cat-file -p 89a024f4c1498b8032809d9f7756f361890efe7e
tree ce02c535193f74c6303280bfef656f4eba1ee5a7
parent d06d127dae88c512857bdeee57a94630ff24b44f
author Julius Angres <julius.angres@outlook.de> 1485895620 +0100
committer GitHub <noreply@github.com> 1485895620 +0100

German translation

sh-4.3$ git cat-file -p ce02c535193f74c6303280bfef656f4eba1ee5a7 | grep patterns
040000 tree 5f620074399f4163dc88927a717a85175b9e4595	patterns

sh-4.3$ git cat-file -p 5f620074399f4163dc88927a717a85175b9e4595 |grep 065
040000 tree f5c12eda473320da33820b67c84b2dd198a1cc0c	065_GOTO

sh-4.3$ git cat-file -p f5c12eda473320da33820b67c84b2dd198a1cc0c |grep main_DE.tex
100644 blob 9bcc3b15520a7f3529aa60f7004fcc551ce200a5	main_DE.tex

sh-4.3$ git cat-file -p 9bcc3b15520a7f3529aa60f7004fcc551ce200a5 | md5sum
bcb59437c8f21ff5d5dc18907b828522  -

Now, the version I commited:
sh-4.3$ git cat-file -p 0480d1ada862e0e6857c687dd3dbb59520724a54
tree 467b47e1c4823ad19e6d7530b7c8ff86cb5c18bc
parent e0907274994c906ecb12008dd405366730d98c6d
author Marc Remy <mremy@gmx.ch> 1485944035 +0100
committer Marc Remy <mremy@gmx.ch> 1485944035 +0100

Strange state after git pull

I didn't change anything, after the last git pull, git status showed a modified file, so I just commit the state.
Maybe an auto convertion somewhere ?

sh-4.3$ git cat-file -p 467b47e1c4823ad19e6d7530b7c8ff86cb5c18bc | grep patterns
040000 tree 95ca1e2d04ee267e6469d8d2d5fdd553e212f374	patterns

sh-4.3$ git cat-file -p 95ca1e2d04ee267e6469d8d2d5fdd553e212f374 | grep 065_GOTO
040000 tree 33f073efef8322fa2ead5b06801f4ea7665d5f61	065_GOTO

sh-4.3$ git cat-file -p 33f073efef8322fa2ead5b06801f4ea7665d5f61 | grep main_DE.tex
100644 blob 6073516f76c8abf6b10ae3d6323b398109037722	main_DE.tex

sh-4.3$ git cat-file -p 6073516f76c8abf6b10ae3d6323b398109037722 |md5sum
2b6b741efbcddaae5b7be48ce58b3319  -

Okay, the 2 versions are different.

sh-4.3$ git cat-file -p 9bcc3b15520a7f3529aa60f7004fcc551ce200a5 >/tmp/m1.tex
sh-4.3$ git cat-file -p 6073516f76c8abf6b10ae3d6323b398109037722 >/tmp/m2.tex
sh-4.3$ md5sum /tmp/m1.tex /tmp/m2.tex patterns/065_GOTO/main_DE.tex
bcb59437c8f21ff5d5dc18907b828522  /tmp/m1.tex
2b6b741efbcddaae5b7be48ce58b3319  /tmp/m2.tex
bcb59437c8f21ff5d5dc18907b828522  patterns/065_GOTO/main_DE.tex

With "vim -b", I've seen that "/tmp/m2.tex" contains only CR!
Let check with a non problematic file:

sh-4.3$ git log patterns/03_printf/main_FR.tex 
commit 90153f248ac12a2731c916d401fd9b862710ada8
Author: Marc Remy <mremy@gmx.ch>
Date:   Sun Jan 29 17:43:57 2017 +0100

    French: translation of patterns/03_printf/

sh-4.3$ git cat-file -p 90153f248ac12a2731c916d401fd9b862710ada8
tree d347f9f045bd0e723b2df6f9c64ebcf79f9f3e95
parent ca47124f260974179b5c10b39fb8388f56babf59
author Marc Remy <mremy@gmx.ch> 1485708237 +0100
committer Marc Remy <mremy@gmx.ch> 1485708517 +0100

French: translation of patterns/03_printf/

sh-4.3$ git cat-file -p d347f9f045bd0e723b2df6f9c64ebcf79f9f3e95 | grep patterns
040000 tree 4960c4ff1d1e6a81abcd9ebca594f0a60dee8fc3	patterns

sh-4.3$ git cat-file -p 4960c4ff1d1e6a81abcd9ebca594f0a60dee8fc3 |grep 03_printf
040000 tree 108f4ddc48dc0514606128e48ac991cd2d9174b5	03_printf

sh-4.3$ git cat-file -p 108f4ddc48dc0514606128e48ac991cd2d9174b5 | grep main_FR.tex
100644 blob 8757b5a637c7f6bc12fee9df37a36b277a6f391f	main_FR.tex

sh-4.3$ git cat-file -p 8757b5a637c7f6bc12fee9df37a36b277a6f391f | md5sum
4fa092dda1b402df768d126620e37847  -

sh-4.3$ md5sum patterns/03_printf/main_FR.tex
739a3c902b535e7d9717b6e52e2b921d  patterns/03_printf/main_FR.tex

The file stored in the blob isn't the same as the one on the git  directory tree! (for end of line management)
sh-4.3$ git cat-file -p 8757b5a637c7f6bc12fee9df37a36b277a6f391f > /tmp/p0.tex

sh-4.3$ head -1 /tmp/p0.tex | hexdump
0000000 735c 6365 6974 6e6f 5c7b 7250 6e69 6674
0000010 6553 6576 6172 416c 6772 6d75 6e65 7374
0000020 6553 7463 6f69 4e6e 6d61 7d65 000a     
000002d

sh-4.3$ head -1 patterns/03_printf/main_FR.tex|hexdump
0000000 735c 6365 6974 6e6f 5c7b 7250 6e69 6674
0000010 6553 6576 6172 416c 6772 6d75 6e65 7374
0000020 6553 7463 6f69 4e6e 6d61 7d65 0a0d     
000002e

Now, I understand why git wanted to commit with "0d" only, instead of "0a0d" on my first message inthis thread !

So, the commits coming from @JAngres are with CRLF in the blob of text file, so we will have to commit them again with LF only, as git modify automaticly (but don't commit...).
I don't know if you can configure something, or if it's just your versions which are too old...
At least, we know what happen now! (and I can play again to world of translation)

**Comment by dennis714** [comment]
Thanks for your investigation!

**Comment by dennis714** [comment]
BTW, EOLs for *.tex is set to CRLF in .gitattributes file long time ago: https://github.com/dennis714/RE-for-beginners/blob/master/.gitattributes

**Comment by mremy** [comment]
It's the git software used, which didn't follow the repo configuration, maybe too old to handle all of the configuration directives.
@JAngres : can you write down me the software name & version you're using for git ? And the vesion of Texlipse & Eclipse too please ? 
I would like to give a try on a vm. Maybe the (real) solution is not that far away.

**Comment by dennis714** [comment]
@JAngres before you adding and committing new translated .tex file, please do hexdump and see what EOLs are used there. Just to be sure.

**Comment by JAngres** [comment]
Hi,

@mremy: I used Eclipse Neon.2 (4.6.2) with EGit 4.6.0 and Texlipse 1.5.0. However, I committed some of the files directly via github upload facility since I didn't translate them on my own computer. Hope this helps.

@dennis714: I'll check EOLs on my next commit and post the result.

On 04.02.2017 08:57, Dennis Yurichev wrote:

@JAngres<https://github.com/JAngres> before you adding and committing new translated .tex file, please do hexdump and see what EOLs are used there. Just to be sure.

**Comment by dennis714** [comment]
So maybe github interface ignores EOL directive in .gitattributes and submit files with LFs?...

**Comment by mremy** [comment]
@dennis714 @JAngres : the issue wasn't in the file (which EOL are fine), but inside the git internal blob. Maybe it happen with the github interface, maybe it's EGit, maybe... Let us know the way you're doing next time. Sure we will find and squash this issue.

**Comment by mremy** [comment]
I wasn't able to reproduce the behavior with the double character at EOL in git blob.
I checked to add a commit through github interface: ok
I tested (on a win7pro vm 64-bit) eclipse neon 2 (java developer, not EE) + texlipse (last version 1.5+egit (last version:4.6.0.201612231935-r): ok
It was with java 1.8 32-bit. I didn't manage to have eclipse 64-bit working (both 32&64-bit java installed).

ok means no strange state after git pull on my Linux, double checked with "hexdump of the file blob".
@JAngres : do you have the same version of egit ?

But I read this int the egit README.md: (https://git.eclipse.org/c/egit/egit.git/)
"Missing Features
----------------
- gitattributes support
In particular CRLF conversion is not yet fully implemented."
I've seen this specific plugin for interaction with github, maybe if worth a try ?
(if the egit version match the one which was good for my test):
https://git.eclipse.org/c/egit/egit-github.git/

**Pull request merged**
