### PR TITLE
German translations

### PR DESCRIPTION
**Pull request by JAngres**
German translations of section patterns/07_jcc/abs.
FYI: I verified with hexdump that EOL is Unix style. OS is Lubuntu 16.10.

### CODE REVIEW

**Comment by dennis714** [comment]
Thanks!

**Comment by dennis714** [comment]
Commit in whatever EOLs which is suitable for you. I'll fix it all by myself.

**Comment by mremy** [comment]
@JAngres : your commits EOL were always fine, it's just the underlying git "stuff" wo didn't seems to work as expected.
Thanks to the genius guys wo used CR, LF or CRLF, big / little endianess, left /right driving, hundred of power plug type, etc.

**Comment by JAngres** [comment]
@mremy : Thanks for you investigation, I appreciate it.

On 06.02.2017 21:42, Marc Remy wrote:

@JAngres<https://github.com/JAngres> : your commits EOL were always fine, it's just the underlying git "stuff" wo didn't seems to work as expected.
Thanks to the genius guys wo used CR, LF or CRLF, big / little endianess, left /right driving, hundred of power plug type, etc.

**Pull request merged**
