### PR TITLE
Typo: 0x010B103A is the third element

### PR DESCRIPTION
**Pull request by mremy**
As it's written after, "counting from zero".
Please check.

### CODE REVIEW

**Comment by dennis714** [comment]
Is this better? https://github.com/dennis714/RE-for-beginners/commit/93de67eeb5629b44b22c4639b7e188f25a0fbd84

**Comment by mremy** [comment]
I still have doubt/question.
I think there is a mix-up between the number of the element and the index of this element.
When I count stuff, I never start with 0.
If I have 2 objects, there's the first one and the second one, not the "0th" (I don't know a word for this in French...) and the first.
But, if this objects are indexed, like in an array, I can start the indexing with the index I want, it's my problem to manage it.
If it's like in C array, the first element willl have index 0, the second one will have index 1, which it's quite practical to calculate address in memory ;-)
This important stuff in computing, maybe worth a new part, just after "1.2.2 Numeral systems", called something like"1.2.3 [Arrays | C-arrays | Asm array]", to explain this notion of element, index of this element and address of element in memory (main thing is something like: addr = base + index*size of object, with index starting at 0).
You know this better than me!

**Comment by dennis714** [comment]
There is a mention about question, why arrays are started at 0.
Look at this: https://github.com/dennis714/RE-for-beginners/commit/fe749376676d16483f99e209b2b9decdb52cd156

**Comment by mremy** [comment]
Yes, but indexing is not counting (it's hard to translate this kind of details), so I think this shouldn't be wrote like this (at least in French):
"(can be indexed as 2nd\footnote[...]"
but:
"(can be indexed as 2\footnote[...]"
If you count distinguable stuff, you start with the first, then the second, etc.
If you index them, you can start with the index you want: -10, 0, 1,etc.
Once again, I can explain it in French, but it's quite harder in English.
I hope it's understandable.

**Comment by dennis714** [comment]
OK: https://github.com/dennis714/RE-for-beginners/commit/7d2f04bcfc851fe441615912007171c7386db27f

**Pull request closed without merging**
