### PR TITLE
French: Start to add part 1.7 Stack.

### PR DESCRIPTION
**Pull request by T30rix**
This commit add the French translation of the main file of part
patterns/02_stack.

I did not translated the quotation of D. M. Ritchie and K. Thompson. Should I do it ?

### CODE REVIEW

**Comment by dennis714** [comment]
In my opinion, if you have their book translated to French, you can copy&paste quotation from there.
If not, leave it as is.

**Comment by dennis714** [comment]
And thanks!

**Comment by mremy** [comment]
@T30rix : I guess we have to synchronize ourselves, not avoid to translate the same files.
For the quotation, maybe it was already translated, as @dennis714 wrote.
I didn't search yet, but I translated this file too...
Do you want to finish this directory (02_stack) ?
If yes, I'll go on with 03_printf.
What do you think ?

**Comment by T30rix** [comment]
@mremy : you are right it's a good idea, I will finish the directory 02_stack.
Sorry for the wasted time.
@dennis714 : I started to look for the French translation of the quotation, but I found nothing for the moment...

**Comment by dennis714** [comment]
@T30rix no problems, leave it as is then

**Comment by mremy** [comment]
@T30rix It's not your fault, we (translators) need a kind of synchronization, to avoid this. But I will open an issue to discuss on this, not to pollute this closed pull-request with off topic.

**Pull request merged**
