### PR TITLE
French: Add translation for patterns/015_prolog_epilogue.

### PR DESCRIPTION
**Pull request by T30rix**
This commit add the French translation for part 1.6 Recursion.

### CODE REVIEW

**Comment by dennis714** [comment]
Thanks!

**Comment by dennis714** [comment]
How to credit you properly? Name, surname?

**Comment by T30rix** [comment]
Yes you can use : Téo Dacquet.

Thank you,

-- 
Téo Dacquet

2017-01-13 11:30 GMT+00:00 Dennis Yurichev <notifications@github.com>:

**Comment by dennis714** [comment]
Thanks! https://github.com/dennis714/RE-for-beginners/commit/897fef5fbc69cdc758eb0a2f5c70f2951b9fec04

**Pull request merged**
